name: Run Shell Script and Capture Output

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Grant execute permissions to the script
        run: chmod +x commands.sh  # Ensure script is executable

      - name: Run commands.sh and pipe output
        run: |
          ./commands.sh 2>&1 | tee output.txt  # Pipe stdout & stderr to output.txt

      - name: Check for expected string in output
        run: |
          if grep -q "ERR_REQUIRE_CYCLE_MODULE" output.txt; then
            echo "✅ Expected string found! Bug reproduced!"
            exit 0  # Success
          else
            echo "❌ Expected string NOT found! Bug did not reproduce!"
            exit 1  # Fail workflow
          fi
