name: Run Shell Script on Multiple Environments

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Define multiple OS
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Grant execute permissions to the script (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x commands.sh  # Ensure script is executable

      - name: Run commands.sh and pipe output (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          ./commands.sh 2>&1 | tee output.txt  # Pipe stdout & stderr to output.txt

      - name: Run commands.sh and pipe output (Windows)
        if: runner.os == 'Windows'
        shell: bash  # Use Bash shell on Windows
        run: |
          bash commands.sh 2>&1 | tee output.txt  # Execute script via Bash

      - name: Check for expected string in output
        run: |
          if grep -q "ERR_REQUIRE_CYCLE_MODULE" output.txt; then
            echo "✅ Expected string found! Bug reproduced!"
            exit 0  # Success
          else
            echo "❌ Expected string NOT found! Bug did not reproduce!"
            exit 1  # Fail workflow
          fi
        shell: bash  # Ensure it runs correctly on all platforms
