name: Run Shell Script and Check Output

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Source the Shell Script and Check stdout
        run: |
          OUTPUT=$(source ./script.sh | tee /dev/tty)  # Capture stdout
          echo "Script Output: $OUTPUT"

          if echo "$OUTPUT" | grep -q "ERR_REQUIRE_CYCLE_MODULE"; then
            echo "✅ Bug successfully reproduced!"
            exit 0  # Success
          else
            echo "❌ Bug NOT reproduced!"
            exit 1  # Fail workflow
          fi
        shell: bash
